# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Race date')),
                ('type', models.CharField(choices=[('Sweep', 'Sweep'), ('Sculling', 'Sculling')], max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
        ),
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mu', models.FloatField()),
                ('sigma', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='crew',
            field=models.ManyToManyField(to='rowing.Rower'),
        ),
        migrations.AddField(
            model_name='result',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rowing.Race'),
        ),
    ]
