# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='mu',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='rower',
            name='sigma',
            field=models.FloatField(default=8.333333333333334),
        ),
    ]
