# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0003_auto_20170502_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='r_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
