# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0004_auto_20170502_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='date',
            new_name='r_date',
        ),
    ]
