# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0005_auto_20170502_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='type',
            new_name='r_type',
        ),
    ]
