# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0007_auto_20170503_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rower',
            old_name='mu',
            new_name='mu_scull',
        ),
        migrations.RenameField(
            model_name='rower',
            old_name='sigma',
            new_name='sigma_scull',
        ),
        migrations.AddField(
            model_name='rower',
            name='mu_sweep',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='rower',
            name='sigma_sweep',
            field=models.FloatField(default=8.333333333333334),
        ),
    ]
