# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0008_auto_20170503_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rowing.Competition')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rowing.Event'),
            preserve_default=False,
        ),
    ]
