# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0009_auto_20170503_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='rower',
            name='nationality',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
