# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0011_auto_20170507_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('entries', models.ManyToManyField(to='rowing.Result')),
            ],
        ),
    ]
