# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0012_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='entries',
        ),
        migrations.AddField(
            model_name='result',
            name='entries',
            field=models.ManyToManyField(to='rowing.Club'),
        ),
    ]
