# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0014_auto_20170508_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sweep', 'Sweep'), ('Sculling', 'Sculling')], default='Sweep', max_length=10)),
                ('mu', models.FloatField(default=100.0)),
                ('sigma', models.FloatField(default=8.333333333333334)),
                ('date', models.DateField(verbose_name='Score date')),
            ],
        ),
        migrations.RemoveField(
            model_name='race',
            name='type',
        ),
        migrations.RemoveField(
            model_name='rower',
            name='mu_scull',
        ),
        migrations.RemoveField(
            model_name='rower',
            name='mu_sweep',
        ),
        migrations.RemoveField(
            model_name='rower',
            name='sigma_scull',
        ),
        migrations.RemoveField(
            model_name='rower',
            name='sigma_sweep',
        ),
        migrations.AddField(
            model_name='event',
            name='distance',
            field=models.CharField(default='2000m', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Sweep', 'Sweep'), ('Sculling', 'Sculling')], default='Sweep', max_length=10),
        ),
        migrations.AddField(
            model_name='rower',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('W', 'W'), ('U', 'U')], default='M', max_length=1),
        ),
    ]
