# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0016_score_rower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='date',
        ),
        migrations.AddField(
            model_name='score',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rowing.Race'),
            preserve_default=False,
        ),
    ]
