# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0017_auto_20170508_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='type',
        ),
    ]
