# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0019_score_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='race',
        ),
    ]
