# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0020_remove_score_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
