# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0022_auto_20170708_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[(0, 'TT/Heat/Single race'), (1, 'Semi-Final'), (2, 'Final')], default=0),
        ),
    ]
