# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-08 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0023_auto_20170708_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreranking',
            name='delta_mu_sigma',
            field=models.FloatField(default=90.0),
        ),
    ]
