# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0025_scoreranking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='rower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowing.Rower'),
        ),
    ]
