# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-24 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0027_auto_20170722_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='complete',
            field=models.BooleanField(default=True, help_text='If set to True (checked) the Race will be published and will be used in calculating scores. Leave unchecked for incomplete races. Useful for big races that need to be done in chunks.'),
        ),
    ]
