# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-17 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0028_race_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('value', models.TimeField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['comp__name', 'name']},
        ),
        migrations.AlterField(
            model_name='result',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowing.Race'),
        ),
        migrations.AddField(
            model_name='time',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowing.Result'),
        ),
    ]
