# Generated by Django 2.0.6 on 2018-06-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0029_auto_20180518_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['order']},
        ),
    ]
