# Generated by Django 2.0.6 on 2018-07-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0031_club_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Sweep', 'Sweep'), ('Sculling', 'Sculling'), ('Lwt Sweep', 'Lightweight Sweep'), ('Lwt Scull', 'Lightweight Sculling'), ('Para-Sweep', 'Adaptive Sweep'), ('Para-Sculling', 'Adaptive Sculling')], default='Sweep', max_length=20),
        ),
    ]
