# Generated by Django 2.0.6 on 2018-07-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0033_auto_20180702_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Sweep', 'Sweep'), ('Sculling', 'Sculling'), ('Lwt Sweep', 'Lightweight Sweep'), ('Lwt Sculling', 'Lightweight Sculling'), ('Para-Sweep', 'Para-Sweep'), ('Para-Sculling', 'Para-Sculling')], default='Sweep', max_length=20),
        ),
    ]
