# Generated by Django 2.0.6 on 2018-07-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0034_auto_20180702_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreranking',
            name='sr_type',
            field=models.CharField(choices=[('Current', 'Current'), ('All time', 'All time')], default='Current', max_length=20),
        ),
    ]
