# Generated by Django 2.0.6 on 2018-07-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0035_scoreranking_sr_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreranking',
            name='type',
            field=models.CharField(default='Sweep', max_length=20),
        ),
    ]
