# Generated by Django 2.0.6 on 2018-07-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0039_auto_20180703_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knockoutrace',
            name='child',
        ),
        migrations.RemoveField(
            model_name='knockoutrace',
            name='parent_b',
        ),
        migrations.RemoveField(
            model_name='knockoutrace',
            name='parent_t',
        ),
        migrations.AddField(
            model_name='knockoutrace',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='rowing.KnockoutRace'),
        ),
        migrations.AlterField(
            model_name='knockoutrace',
            name='knockout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rowing.EventInstance'),
        ),
    ]
