# Generated by Django 2.0.6 on 2018-07-03 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0040_auto_20180703_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knockoutrace',
            name='parent',
        ),
        migrations.AddField(
            model_name='knockoutrace',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='rowing.KnockoutRace'),
        ),
    ]
