# Generated by Django 2.0.6 on 2018-07-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0041_auto_20180703_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='knockoutrace',
            name='bye',
            field=models.BooleanField(default=False),
        ),
    ]
