# Generated by Django 2.0.6 on 2018-07-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0042_knockoutrace_bye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='clubs',
            field=models.ManyToManyField(blank=True, to='rowing.Club'),
        ),
        migrations.AlterField(
            model_name='result',
            name='crew',
            field=models.ManyToManyField(blank=True, to='rowing.Rower'),
        ),
        migrations.AlterField(
            model_name='result',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
