# Generated by Django 2.0.6 on 2018-07-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0043_auto_20180704_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='clubs',
            field=models.ManyToManyField(to='rowing.Club'),
        ),
    ]
