# Generated by Django 2.0.6 on 2018-07-05 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0045_auto_20180704_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='CumlProb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crewname', models.CharField(max_length=100)),
                ('day', models.DateField()),
                ('cumlprob', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchProb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crewAname', models.CharField(max_length=100)),
                ('crewBname', models.CharField(max_length=100)),
                ('day', models.DateField()),
                ('winprob', models.FloatField()),
                ('knockout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowing.EventInstance')),
            ],
        ),
    ]
