# Generated by Django 2.0.6 on 2018-07-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0046_cumlprob_matchprob'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumlprob',
            name='dayn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matchprob',
            name='dayn',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
