# Generated by Django 2.0.6 on 2018-07-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0047_auto_20180705_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumlprob',
            name='knockout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rowing.EventInstance'),
            preserve_default=False,
        ),
    ]
