# Generated by Django 2.0.6 on 2018-07-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0049_knockoutcrews'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinstance',
            name='rounds',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='knockoutcrews',
            name='startingslot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
