# Generated by Django 2.0.6 on 2018-07-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0050_auto_20180705_2307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnockoutCrews',
            new_name='KnockoutCrew',
        ),
    ]
