# Generated by Django 2.0.6 on 2018-07-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0052_eventinstance_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
