# Generated by Django 2.0.6 on 2018-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0054_knockoutrace_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rower',
            name='iscox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventinstance',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='race',
            name='complete',
            field=models.BooleanField(default=True, help_text='If set to True (checked) the Race will be used in calculating scores. Leave unchecked for incomplete races. Useful for big races that need to be done in chunks.'),
        ),
    ]
