# Generated by Django 2.0.6 on 2018-07-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0056_race_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='public',
        ),
        migrations.AlterField(
            model_name='race',
            name='complete',
            field=models.BooleanField(default=True, help_text='If set to True (checked) the Race will be used in calculating scores and displayed publicly. Leave unchecked for incomplete races. Useful for big races that need to be done in chunks.'),
        ),
    ]
