# Generated by Django 2.2.2 on 2019-06-23 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0058_auto_20190623_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreranking',
            name='rower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowing.Rower'),
        ),
    ]
