# Generated by Django 2.2.2 on 2019-06-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0059_auto_20190623_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='wrid',
            field=models.IntegerField(blank=True, null=True, verbose_name='World Rowing ID'),
        ),
    ]
