# Generated by Django 2.1.4 on 2019-07-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0060_auto_20190624_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='rnumber',
            field=models.IntegerField(blank=True, help_text='If helpful, this can be used to store race numbers.', null=True, verbose_name='Race Number'),
        ),
    ]
