# Generated by Django 2.1.4 on 2019-07-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0062_alias'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('rower', 'value')},
        ),
    ]
