# Generated by Django 2.1.4 on 2019-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0064_auto_20190719_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='country',
            field=models.CharField(blank=True, default='UK', max_length=200, null=True),
        ),
    ]
