# Generated by Django 2.2.4 on 2019-08-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0067_alias_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rower',
            name='wrid',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='World Rowing ID'),
        ),
    ]
