# Generated by Django 2.1.11 on 2019-08-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0068_auto_20190809_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Predecessor', 'Predecessor'), ('Successor', 'Successor')], max_length=15)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rowing.Race')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='rowing.Race')),
            ],
        ),
        migrations.RenameModel(
            old_name='EventInstance',
            new_name='Fixture',
        ),
    ]
