# Generated by Django 2.1.11 on 2019-08-25 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0069_auto_20190825_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racelink',
            old_name='race',
            new_name='startrace',
        ),
        migrations.RemoveField(
            model_name='racelink',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='racelink',
            name='type',
        ),
        migrations.AddField(
            model_name='race',
            name='progression',
            field=models.ManyToManyField(through='rowing.RaceLink', to='rowing.Race'),
        ),
        migrations.AddField(
            model_name='racelink',
            name='endrace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='endrace', to='rowing.Race'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racelink',
            name='positions',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
    ]
