# Generated by Django 3.0.6 on 2020-05-16 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0070_auto_20190825_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='year',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rowing.Event'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rowing.Competition')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rowing.Edition'),
        ),
    ]
