# Generated by Django 3.0.6 on 2020-05-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0071_auto_20200517_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='distance',
        ),
        migrations.AddField(
            model_name='race',
            name='distance',
            field=models.IntegerField(default=2000, help_text='The race distance, in metres.'),
        ),
        migrations.AddField(
            model_name='race',
            name='fixture',
            field=models.ForeignKey(blank=True, help_text='If this race is a part of a wider fixture (e.g. a specific regatta), specify it here. Optional - not needed for single race events e.g. the Boat Race', null=True, on_delete=django.db.models.deletion.PROTECT, to='rowing.Fixture'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rowing.Edition'),
            preserve_default=False,
        ),
    ]
