# Generated by Django 3.0.6 on 2020-05-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0072_auto_20200517_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='boatsize',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Pair/Double'), (4, 'Four/Quad'), (8, 'Eight/Octuple'), (0, 'Other')], default=1),
        ),
        migrations.AddField(
            model_name='fixture',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
