# Generated by Django 3.0.6 on 2020-05-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0073_auto_20200517_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='rounds',
        ),
    ]
