# Generated by Django 3.0.6 on 2020-05-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0074_auto_20200517_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='event',
        ),
    ]
