# Generated by Django 3.0.6 on 2020-05-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0075_remove_fixture_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='location',
        ),
    ]
