# Generated by Django 3.0.6 on 2020-05-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0076_remove_fixture_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='edition',
        ),
        migrations.AddField(
            model_name='fixture',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
