# Generated by Django 3.0.6 on 2020-05-17 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0077_auto_20200518_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rowing.Edition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixture',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rowing.Event'),
            preserve_default=False,
        ),
    ]
