# Generated by Django 3.0.6 on 2020-05-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0078_auto_20200518_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
