# Generated by Django 3.0.6 on 2020-05-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0079_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterField(
            model_name='racelink',
            name='endrace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_races', to='rowing.Race'),
        ),
        migrations.AlterField(
            model_name='racelink',
            name='positions',
            field=models.CharField(help_text='Specify which positions will progress as a comma-separated string e.g. 1,2,3', max_length=100),
        ),
        migrations.AlterField(
            model_name='racelink',
            name='startrace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_races', to='rowing.Race'),
        ),
    ]
