# Generated by Django 3.0.6 on 2020-05-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0080_auto_20200519_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racelink',
            old_name='endrace',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='racelink',
            old_name='startrace',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='race',
            name='progression',
        ),
        migrations.AddField(
            model_name='racelink',
            name='fixture',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='rowing.Fixture'),
            preserve_default=False,
        ),
    ]
