# Generated by Django 3.0.6 on 2020-05-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0081_auto_20200520_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='round',
            field=models.IntegerField(blank=True, help_text='In a multi-round fixture, use this to differentiate between F, SF, Reps, QF, Heat 2, Heat 1, TTs etc', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='boatsize',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Pair/Double'), (4, 'Four/Quad'), (8, 'Eight/Octuple'), (0, 'Other')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='order',
            field=models.PositiveSmallIntegerField(choices=[(0, 'TT/Heat/Single race'), (1, 'Semi-Final'), (2, 'Final')], default=0, help_text='Used to differentiate between races held on same day for rower scores. To be deprecated'),
        ),
    ]
