# Generated by Django 3.0.6 on 2020-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0082_auto_20200521_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='slot',
            field=models.IntegerField(blank=True, help_text='Within a round, this is the order of races, top to bottom on the tree. E.g. H1 will be round 1, slot 1; Heat 2 will be round 1, slot 2 etc; SFAB1 will be round 2, slot 1 etc.', null=True),
        ),
    ]
