# Generated by Django 3.0.6 on 2020-05-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0083_race_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='starttime',
            field=models.TimeField(blank=True, help_text='When the race was scheduled to take place e.g. 13:00. NOT the racing results.', null=True, verbose_name='Race time'),
        ),
    ]
