# Generated by Django 3.0.6 on 2020-05-31 20:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0084_race_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_name', models.CharField(max_length=100)),
                ('submitter_email', models.EmailField(max_length=254)),
                ('submitted_ip', models.GenericIPAddressField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('submitted', models.DateTimeField(auto_now_add=True, verbose_name='Submitted on')),
            ],
        ),
    ]
