# Generated by Django 3.0.6 on 2020-05-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0085_proposedchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedchange',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proposedchange',
            name='model_pk',
            field=models.IntegerField(help_text='The primary key of the model.', null=True),
        ),
    ]
