# Generated by Django 3.0.6 on 2020-06-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0086_auto_20200601_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedchange',
            name='operation',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('merge', 'Merge')], max_length=10, null=True),
        ),
    ]
