# Generated by Django 4.2.27 on 2026-01-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0087_proposedchange_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedchange',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['date'], name='rowing_race_date_2d1727_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['complete'], name='rowing_race_complet_8b3d38_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['date', 'complete'], name='rowing_race_date_732e78_idx'),
        ),
        migrations.AddIndex(
            model_name='race',
            index=models.Index(fields=['event', 'date'], name='rowing_race_event_i_1ee753_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['rower'], name='rowing_scor_rower_i_bbc71d_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['result'], name='rowing_scor_result__eec942_idx'),
        ),
        migrations.AddIndex(
            model_name='scoreranking',
            index=models.Index(fields=['type', 'sr_type', 'date'], name='rowing_scor_type_0391eb_idx'),
        ),
        migrations.AddIndex(
            model_name='scoreranking',
            index=models.Index(fields=['delta_mu_sigma'], name='rowing_scor_delta_m_8dab00_idx'),
        ),
        migrations.AddIndex(
            model_name='scoreranking',
            index=models.Index(fields=['rower', 'type', 'sr_type'], name='rowing_scor_rower_i_f808a5_idx'),
        ),
    ]
