# Generated by Django 4.2.27 on 2026-01-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rowing', '0087_proposedchange_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedchange',
            name='data',
            field=models.JSONField(),
        ),
    ]
