# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 00:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180218_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 0, 28, 37, 532069, tzinfo=utc), verbose_name='Published on'),
        ),
    ]
