# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 00:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180219_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 0, 29, 12, 477972, tzinfo=utc), verbose_name='Published on'),
        ),
    ]
