# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-19 00:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180219_0029'),
    ]

    operations = [
        '''migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),'''
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 0, 40, 8, 869933, tzinfo=utc), verbose_name='Published on'),
        ),
    ]
